### ISSUE TITLE
Linking to specific line in code make comments unreadable

### ISSUE THREAD

**Issue by matrixik** [rmcfadzean/stylish-github#16]
Hello, thank you for great theme.

Linking to specific line in code make comments unreadable:
https://github.com/rmcfadzean/stylish-github/blob/master/gulpfile.js#L59-L69
![screenshot from 2017-12-04 12-52-33](https://user-images.githubusercontent.com/201930/33551566-0a544e26-d8f2-11e7-9cb5-55a2bb87ccc4.png)

Also as you can see some code parts also becoming hardly readable.

**Comment by blindingstars** [comment]
Thanks for letting us know, @matrixik! We admittedly have been lazy about updates here.

Highlighted code should now be a whole lot prettier:

![image](https://user-images.githubusercontent.com/6765732/33799818-e00b082a-dcf8-11e7-81ae-00e8f9d12ecc.png)

**Comment by matrixik** [comment]
Great, looks a lot better, thank you.
